pipeline {
    agent any
    tools {
      maven 'Global Maven'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install -Denforcer.fail=false'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Denforcer.fail=false'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete') {
            steps {
                echo 'Pipeline Completed'
            }
        }
    }
}
